FROM ghcr.io/mlflow/mlflow:v2.19.0



RUN pip install psycopg2-binary

COPY mlflow_entrypoint.sh /usr/local/bin/entrypoint.sh

RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
